export const FETCH_DATA = 'DATA/FETCH_DATA'
export const REQUEST_DATA = 'DATA/REQUEST_DATA'

export const FILTER_ORDERS = 'DATA/FILTER_ORDERS' 
export const FILTER_PLANT = 'DATA/FILTER_PLANT'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

